version: '3'

services:
  mongo:
    container_name: vfastsoft_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abcd1234
      MONGO_INITDB_DATABASE: vfastadmin

  backend:
    container_name: vfastsoft_be
    image: registry.vfastsoft.com/vfast/v-fast_api:latest
    ports:
      - '20011:3000'
    environment:
      # DB Config
      - DB_MONGO_HOST=mongo # `mongo` là tên của service mysql phía trên
      - DB_MONGO_PORT=27017 # port mặc định của mysql
      - DB_MONGO_NAME=vfastadmin # giống phía trên
      - DB_MONGO_USER=root # mặc định là root
      - DB_MONGO_PASSWORD=abcd1234 # giống phía trên
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    depends_on:
      - mongo
