version: '3'

services:
  mongo:
    container_name: vfastsoft_db
    image: khacdatdo/mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abcd1234
      MONGO_INITDB_DATABASE: vfastadmin
    volumes:
      - ./data/db:/data/db
  backend:
    container_name: vfastsoft_be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: vfast-api:latest
    ports:
      - '3000:3000'
    environment:
      - FOLDER_UPLOAD=public
      # DB Config
      - DB_MONGO_HOST=mongo # `mongo` là tên của service mysql phía trên
      - DB_MONGO_PORT=27017 # port mặc định của mysql
      - DB_MONGO_USER=root # mặc định là root
      - DB_MONGO_PASSWORD=abcd1234 # giống phía trên
      - DB_MONGO_DATABASE=vfastadmin
    depends_on:
      - mongo
