version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: vfastadmin
    ports:
      - '27018:27017'

  backend:
    container_name: backend
    image: test:latest
    ports:
      - '4000:3000'
    environment:
      # DB Config
      - DB_MONGO_HOST=mongo # `mongo` là tên của service mysql phía trên
      - DB_MONGO_PORT=27017 # port mặc định của mysql
      - DB_MONGO_NAME=vfastadmin # giống phía trên
      - DB_MONGO_USER=root # mặc định là root
      - DB_MONGO_PASSWORD=example # giống phía trên
    depends_on:
      - mongo
